package src.main.java.Pageclasses;

import java.lang.Exception;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.TimeUnit;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.ExpectedCondition;
import org.openqa.selenium.support.ui.Select;

import src.main.java.baseClasses.BasePage;

/**
 * This class was automatically generated by TestProject
 * Project: Flight Booking Form
 * Test: Registration page
 * Generated by: shriram s shriram s (srimd0205@gmail.com)
 * Generated on Tue Nov 22 07:01:12 GMT 2022.
 */
public class RegistrationPage  extends BasePage{
	/**
     * Page class.
     * @param driver
     */
	
	public RegistrationPage(WebDriver driver) {
        super(driver); 
        PageFactory.initElements( driver, this);
        }
	

	
	public void openBrowser(String URL) 
	{
       this.driver.navigate().to(URL);
       // clickWhenVisible(usernameLocator);
        //return (SF_LoginPage) openPage(SF_LoginPage.class);
    }
  /**
   * Fname_registration test parameter
   */
  public String Fname_registration = "";

  /**
   * Lname_registration test parameter
   */
  public String Lname_registration = "";

  /**
   * phno_registration test parameter
   */
  public String phno_registration = "";

  /**
   * email_registration test parameter
   */
  public String email_registration = "";

  /**
   * addr_registration test parameter
   */
  public String addr_registration = "";

  /**
   * city_registration test parameter
   */
  public String city_registration = "";

  /**
   * state_registration test parameter
   */
  public String state_registration = "";

  /**
   * pincode_registration test parameter
   */
  public String pincode_registration = "";

  /**
   * countyr_registration test parameter
   */
  public String countyr_registration = "";

  /**
   * username test parameter
   */
  public String username = "";

  /**
   * password test parameter
   */
  public String password = "";

  /**
   * COnfirm_password test parameter
   */
  public String COnfirm_password = "";

  /**
   * ApplicationURL test parameter
   */
  public String ApplicationURL = "";

  public void execute(String Fname_registration,String Lname_registration,String phno_registration,String email_registration,String addr_registration,String city_registration,String state_registration,String pincode_registration,String countyr_registration,String username,String password,String COnfirm_password ) throws Exception {
    //driver = parentDriver;
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;

    // 1. Navigate to 'https://vins-udemy.s3.amazonaws.com/docker/docker-book-flight.html#'
    GeneratedUtils.sleep(500);
    //driver.navigate().to("https://vins-udemy.s3.amazonaws.com/docker/docker-book-flight.html#");

    // 2. Type '{{Fname_registration}}' in 'firstName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='firstName']");
    driver.findElement(by).sendKeys(Fname_registration);

    // 3. Type '{{Lname_registration}}' in 'lastName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='lastName']");
    driver.findElement(by).sendKeys(Lname_registration);

    // 4. Type '{{phno_registration}}' in 'phone'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='phone']");
    driver.findElement(by).sendKeys(phno_registration);

    // 5. Type '{{email_registration}}' in 'userName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#userName");
    driver.findElement(by).sendKeys(email_registration);

    // 6. Scroll window by ('0','100')
    GeneratedUtils.sleep(500);
    ((JavascriptExecutor)driver).executeScript("window.scrollBy(0,100)","");

    // 7. Scroll window by ('0','56')
    GeneratedUtils.sleep(500);
    ((JavascriptExecutor)driver).executeScript("window.scrollBy(0,56)","");

    // 8. Type '{{addr_registration}}' in 'address1'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='address1']");
    driver.findElement(by).sendKeys(addr_registration);

    // 9. Type '{{city_registration}}' in 'city'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='city']");
    driver.findElement(by).sendKeys(city_registration);

    // 10. Type '{{state_registration}}' in 'state'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='state']");
    driver.findElement(by).sendKeys(state_registration);

    // 11. Type '{{pincode_registration}}' in 'postalCode'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='postalCode']");
    driver.findElement(by).sendKeys(pincode_registration);

    // 12. Click 'country'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='country']");
    driver.findElement(by).click();

    // 13. Select the '{{countyr_registration}}' option in 'country'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='country']");
    (new Select(driver.findElement(by))).selectByValue(countyr_registration);

    // 14. Type '{{username}}' in 'email'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#email");
    driver.findElement(by).sendKeys(username);

    // 15. Type '{{password}}' in 'password'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='password']");
    driver.findElement(by).sendKeys(password);

    // 16. Type '{{COnfirm_password}}' in 'confirmPassword'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='confirmPassword']");
    driver.findElement(by).sendKeys(COnfirm_password);

    // 17. Click 'register'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#register-btn");
    driver.findElement(by).click();

  }



@Override
protected ExpectedCondition<?> getPageLoadCondition() {
	// TODO Auto-generated method stub
	return null;
}

  
}
